// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function MainLayout({ children }) {
    return (
        <>
            {/* <LocalIntlProvider messages={messages}> */}
            {children}
            {/* </LocalIntlProvider> */}
        </>
    );
}
