export const endpoints = {
    auth: {
        register: 'register',
        login: 'login',
        changePassword: 'website/change-password',
        forgotPassword: 'forgot-password',
        recoverPassword: 'recover-password',
        logout: 'website/logout',
        verifyEmailOtp: 'verify-email-otp',
        verifyEmailToken: 'verify-email-token',
        requestEmailVerificationOtp: 'request-email-verification-otp-token',
    },
    chat: {
        canChat: 'website/chat/can-chat',
        start: 'website/chat/start',
        acceptConversation: 'website/chat/accept-conversation',
        declineConversation: 'website/chat/decline-conversation',
        sendMessage: 'website/chat/send',
        messages: 'website/chat/messages',
        conversations: 'website/chat/conversations',
    },
    customer: {
        fetchProfile: 'website/owner/fetch-profile',
        updateProfile: 'website/owner/update-profile',
        fetchService: 'website/owner/fetch-service',
        updateService: 'website/owner/update-service',
        sitterList: 'website/owner/pet-sitter-list',
        sitterDetail: 'website/owner/pet-sitter-detail',
        alternativeSitterList: 'website/owner/alternative-pet-sitter-list',

        fetchPlan: 'website/owner/fetch-plan',
        createOrder: 'website/owner/create-order',
        updateOrder: 'website/owner/update-order',
        getAllOrders: 'website/owner/get-all-orders',
        getOrder: 'website/owner/get-order/1',
        deleteOrder: 'website/owner/delete-order/1',
        paymentConfig: 'website/owner/payment-config',
        paymentSuccess: 'website/owner/payment-success',
        paymentCancel: 'website/owner/payment-cancel',

        createSubscription: 'website/owner/create-subscription',
        getSubscriptionDetail: 'website/owner/get-subscription-detail',
        activeSubscriptionsOverview: 'website/owner/active-subscriptions-overview',
        cancelSubscription: 'website/owner/cancel-subscription',

        submitReview: 'website/owner/submit-review',
        reviewsGiven: 'website/owner/reviews-given',
        reviewsReceived: 'website/owner/reviews-received',
    },
    sitter: {
        fetchProfile: 'website/sitter/fetch-profile',
        updateProfile: 'website/sitter/update-profile',
        fetchService: 'website/sitter/fetch-service',
        updateService: 'website/sitter/update-service',
        ownerList: 'website/sitter/pet-owner-list',
        ownerDetail: 'website/sitter/pet-owner-detail',

        submitReview: 'website/sitter/submit-review',
        reviewsGiven: 'website/sitter/reviews-given',
        reviewsReceived: 'website/sitter/reviews-received',
    },
    public: {
        sitterList: 'website/pet-sitter-list',
        sitterDetail: 'website/pet-sitter-detail',
        alternativeSitterList: 'website/alternative-pet-sitter-list',
        contactUs: 'website/contact-us',
        languages: 'languages',
        favoriteAdd: 'website/favorite-add',
        favoriteList: 'website/favorite-list',
        favoriteRemove: 'website/favorite-remove',
        profilePhotoDel: 'website/profile-photo',
        galleryPhotoDel: 'website/gallery-photo',
        faqs: 'faqs',
        siteSettings: 'site-settings',
        blogs: 'blogs',
        blogDetail: 'blogs/:slug',
        recentBlog: 'recent-blog/:id',
    },
};
