import { DM_Sans } from 'next/font/google';
import localFont from 'next/font/local';

import I18nProvider from '@/app/I18nProvider';
import { ModalProvider } from '@/app/ModalProvider';
import QueryProvider from '@/app/QueryProvider';
import StoreProvider from '@/app/StoreProvider';
import ToastProvider from '@/app/ToastProvider';
import ChatSocketProvider from '@/context/ChatSocketProvider';
import 'bootstrap/dist/css/bootstrap.min.css'; // Import Bootstrap CSS
// import NextTopLoader from 'nextjs-toploader'
// import AOSProvider from './AOSProvider'
// import dynamic from 'next/dynamic'
// const DynamicTagManager = dynamic(() => import('@/app/TagManagers'), { ssr: false })
// import Script from 'next/script'
import '@/styles/style.scss';
import SiteSettingsInitializer from '@/components/SiteSettingsInitializer';
import { GoogleOAuthProvider } from '@react-oauth/google';

const DMSans = DM_Sans({
    // ... (lines 16-53 remain unmodified, so let's match the exact text block)
    weight: ['200', '400', '500', '600', '700', '800'],
    display: 'swap',
    subsets: ['latin'],
    variable: '--secondary-font',
});

const AllianceNo2 = localFont({
    src: [
        {
            path: '../../public/fonts/AllianceNo2-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/AllianceNo2-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/AllianceNo2-SemiBold.woff2',
            weight: '600',
            style: 'normal',
        },
        {
            path: '../../public/fonts/AllianceNo2-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
    ],
    variable: '--primary-font',
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

// export const dynamic = 'force-dynamic'; //to make all route SSR

export default function RootLayout({ children }) {
    return (
        <StoreProvider>
            <QueryProvider>
                <SiteSettingsInitializer>
                    <GoogleOAuthProvider
                        clientId={
                            process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ||
                            process.env.GOOGLE_CLIENT_ID
                        }
                    >
                        <html lang="en" data-scroll-behavior="smooth">
                            <body className={`${AllianceNo2.variable} ${DMSans.variable}`}>
                                <I18nProvider>
                                    {/* <NextTopLoader color='#cf963f' showSpinner={false} /> */}
                                    <ToastProvider>
                                        <ChatSocketProvider>
                                            <ModalProvider>{children}</ModalProvider>
                                        </ChatSocketProvider>
                                    </ToastProvider>
                                </I18nProvider>
                            </body>
                        </html>
                    </GoogleOAuthProvider>
                </SiteSettingsInitializer>
            </QueryProvider>
        </StoreProvider>
    );
}
